"""Bake data/*.json into bank.js, so the page needs no data requests at all.

    python tools/build_bank.py            write bank.js
    python tools/build_bank.py --check    fail if bank.js is out of date

The per-topic JSON files stay the source of truth: they are what gets authored and
what tools/validate.py checks. This just inlines them, because eleven fetches were
eleven chances to fail and a reader hit exactly that. A script tag also means the
page works opened straight off disk, which fetch never allowed.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "bank.js"

HEADER = ("/* Generated by tools/build_bank.py. Do not edit.\n"
          "   Source of truth is data/*.json; run the tool after changing them. */\n")


def build():
    index = json.loads((DATA / "index.json").read_text(encoding="utf-8"))
    topics = {}
    for topic in index["topics"]:
        key = topic["key"]
        topics[key] = json.loads((DATA / f"{key}.json").read_text(encoding="utf-8"))
    payload = {"index": index, "topics": topics}
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
    count = sum(len(v) for v in topics.values())
    return HEADER + "window.BANK = " + body + ";\n", count


def main() -> int:
    text, n = build()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print("bank.js is out of date. Run: python tools/build_bank.py")
            return 1
        print(f"bank.js is current, {n} questions, {len(text) // 1024}KB")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.name}, {n} questions, {len(text) // 1024}KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
