"""Builds statecraft/data.json, the single file the page reads.

TWO THINGS HAPPEN HERE AND ONLY ONE OF THEM IS PLUMBING.

The plumbing is the guard: the validations in test_data.py run first, and if any
of them fails nothing is written. A half-built data file on a page that states
figures is worse than a stale one, so the failure mode is deliberately
"yesterday's data, loudly", never "today's data, quietly wrong".

The substance is the derivation. Every option in policies.py carries a
hand-written `axis` value, the position that option implies on its domain's axis.
Hand values have been wrong twice in ways that reached a live claim, most
recently en_carbon_tax sitting at 180 g/kWh while its ten tagged countries
average about 287. So an option's axis value is now the MEDIAN of the measured
values of the countries tagged to it, computed here at build time from
countries.py.

MEDIAN, not mean, because it is robust to a single classification artefact.
Switzerland reads 33.1 on public health share, against 48 to 85 for the rest of
its option, because WHO counts compulsory Swiss cover as private insurance. A
mean would let that one cell drag the marker; a median will not.

An option with no tagged country, or whose tagged countries have no measured
value for that axis, keeps its hand value. Five options are untagged on purpose
and are the aspirational half of the menu, so a hand value is the only thing
available and that is correct.

`redistribution` is contributed to by the tax, work and family choices and summed
rather than owned by one domain, so those entries stay hand values. Only each
domain's OWN axis is derived.

BOTH VALUES ARE EMITTED. `axis` is the effective value the page uses, `axis_hand`
is what was written by hand, and `axis_basis` says which it is and off how many
countries. Keeping the hand value is what lets a later session ask whether the
judgement or the measurement was wrong, instead of only being able to see that
they differ.
"""

import json
import pathlib
import statistics
import subprocess
import sys

from axes import AXES
from countries import COUNTRIES
from policies import DOMAINS
from timezones import FALLBACK, TIMEZONES

HERE = pathlib.Path(__file__).parent
OUT = HERE / "data.json"

BANNER = ("GENERATED BY build_data.py. Do not edit. Edit policies.py, "
          "countries.py or axes.py and rebuild.")


def measured(axis, codes):
    """The measured values of `codes` on `axis`, skipping what cannot be read.

    A missing key is "no data" and a None value is "does not apply". Neither can
    go into a median, and both are dropped here rather than counted as zero,
    which is the mistake that would quietly pull every derived value towards the
    bottom of its track.

    MATCHABLE COUNTRIES ONLY, decided 30/08/2026 when twenty-five measured-only
    countries were added. A country tag on an option is the claim that that
    country runs that policy, and the thing that holds the claim honest is
    test_option_country_tags_name_a_country_that_holds_that_option, which checks
    the tag against the country's own matrix cell. A measured-only country has no
    matrix, so its tag cannot be checked, and letting an unchecked tag pull the
    marker would put an unverifiable claim on the page dressed as a measurement.
    Five options are tagged to one: de_neutral IE, im_controlled IT, ju_standard
    IE and IT, ju_decriminalised PT, fa_pronatal HU. They contribute nothing
    until those countries are coded, at which point they start contributing and
    the matrix check starts covering them, both automatically.
    """
    cells = {c["code"]: c["indicators"] for c in COUNTRIES if c["matchable"]}
    out = []
    for code in codes:
        cell = cells.get(code, {}).get(axis)
        if cell and cell.get("value") is not None:
            out.append(cell["value"])
    return out


def derive(domain, option):
    """Return (effective axis dict, basis string) for one option.

    The returned dict is a copy: the module-level DOMAINS must not be mutated,
    or importing this from the tests would silently change what the tests are
    testing.
    """
    axis = domain["axis"]
    values = measured(axis, option["countries"])
    effective = dict(option["axis"])
    if not values:
        return effective, "hand"
    effective[axis] = statistics.median(values)
    n = len(values)
    return effective, f"derived from {n} {'country' if n == 1 else 'countries'}"


def effective_axis_values():
    """{option_id: (effective dict, hand dict, basis)} for every option.

    Shared with test_data.py so the bounds check tests the value the page will
    actually plot, rather than a value that is recomputed a second time and could
    drift from this one.
    """
    out = {}
    for d in DOMAINS:
        for o in d["options"]:
            effective, basis = derive(d, o)
            out[o["id"]] = (effective, o["axis"], basis)
    return out


def build():
    derived_count = hand_count = 0
    domains_out = []
    for d in DOMAINS:
        options_out = []
        for o in d["options"]:
            effective, basis = derive(d, o)
            if basis == "hand":
                hand_count += 1
            else:
                derived_count += 1
            out = {k: v for k, v in o.items() if k != "axis"}
            out["axis"] = effective
            out["axis_hand"] = o["axis"]
            out["axis_basis"] = basis
            options_out.append(out)
        domains_out.append({**d, "options": options_out})

    payload = {
        "_banner": BANNER,
        "axes": [{**a, "bounds": list(a["bounds"])} for a in AXES],
        "domains": domains_out,
        "countries": COUNTRIES,
        "timezones": TIMEZONES,
        "fallback": FALLBACK,
    }
    return payload, derived_count, hand_count


def coverage():
    axis_ids = [a["id"] for a in AXES]
    total = len(COUNTRIES) * len(axis_ids)
    have = sum(1 for c in COUNTRIES for a in axis_ids if a in c["indicators"])
    return have, total


def main():
    tests = subprocess.run([sys.executable, "-m", "pytest", "test_data.py", "-q"],
                           cwd=HERE)
    if tests.returncode != 0:
        print("validations failed: data.json NOT rewritten", file=sys.stderr)
        return 1

    payload, derived_count, hand_count = build()
    OUT.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
                   encoding="utf-8")

    options = sum(len(d["options"]) for d in DOMAINS)
    have, total = coverage()
    print(f"\nwrote {OUT.name}")
    print(f"  countries      {len(COUNTRIES)}")
    print(f"  domains        {len(DOMAINS)}")
    print(f"  options        {options}")
    print(f"  axis values    {derived_count} derived from real countries, "
          f"{hand_count} hand")
    print(f"  timezones      {len(TIMEZONES)} mapped, fallback {FALLBACK}")
    print(f"  indicators     {have} of {total} cells ({100 * have / total:.0f}%)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
