"""The twenty launch countries.

Twenty is a staging decision, not a design position. Build-out to every country
is tracked in hub-notes TODO.md: the axes are automatable and can go wide long
before the matrix does, because every matrix cell is a human judgement with a
citation behind it.

`choices` is the policy matrix and it is the thing the match runs on. Each cell
is a claim about what the country actually does, and it appears in the reveal
next to that country's name, so it is checked against a source before it ships.

`nonTaxRevenue` is income the state has that is not tax, in % of GDP, and it is
inherited from the starting country rather than chosen. A state's income is tax
PLUS non-tax income, and for nineteen of the twenty the second term rounds to
nothing. For the UAE it is most of the budget. Total capacity is the realised
value of the chosen tax rate plus this, floored at what the country already
spends. See budget.js.

`indicators` carries a value, a year and a source per axis. A value of None is
"does not apply" and must never be confused with a missing key, which is "no
data". Both are handled separately in the reveal.

WHERE THE MATRIX IS THIN, measured 2026-08-29 over all 190 pairs. No pair
matches on all thirteen, so no country is unreachable in the reveal, but the
count of shared cells on the closest pairs is the margin the whole match turns
on:

    11  SE NO   work, defence
    10  SE FI   work, immigration, family
    10  NZ EE   tax, education, immigration
    10  AU NZ   energy, voting, work
     9  NZ CL   healthcare, education, retirement, immigration
     9  NZ CA   education, retirement, voting, justice
     9  NO FI   work, defence, immigration, family
     9  DK FI   housing, energy, defence, immigration

Sweden and Norway are separated by two cells, so a visitor who picks the Nordic
package is sorted between them by the work and defence choices alone. Those two
cells carry more weight than any others in this file, and NZ is the country most
often near the top, which makes its row the one to check first. Re-run the pair
script after any cell change: a correction that looks local can quietly push a
pair to thirteen.
"""

COUNTRIES = [
    {"code": "AU", "name": "Australia", "timezones": ["Australia/Sydney", "Australia/Melbourne",
        "Australia/Brisbane", "Australia/Perth", "Australia/Adelaide", "Australia/Hobart",
        "Australia/Darwin"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_mixed", "education": "ed_deferred",
                 "housing": "ho_market", "retirement": "re_super", "energy": "en_fossil",
                 "speech": "sp_hate_limits", "voting": "vo_preferential", "work": "wo_bargaining",
                 "defence": "de_alliance", "immigration": "im_points", "justice": "ju_tough",
                 "family": "fa_targeted"},
     "indicators": {
         "health_public": {"value": 73.7, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.1, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 1.9, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 30.4, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 29.5, "year": 2021,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 3.2, "year": 2021,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 3.4, "year": 2022,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 1.9, "year": 2022,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.122, "year": 2020,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 525.2, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.915, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 23.11, "year": 2025,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 59.7, "year": 2023,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 170.0, "year": 2025,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "NZ", "name": "New Zealand", "timezones": ["Pacific/Auckland"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_mixed", "education": "ed_deferred",
                 "housing": "ho_market", "retirement": "re_super", "energy": "en_carbon_tax",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_minimum",
                 "defence": "de_alliance", "immigration": "im_points", "justice": "ju_tough",
                 "family": "fa_targeted"},
     "indicators": {
         "health_public": {"value": 77.7, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.2, "year": 2023,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 1.2, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 28.2, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 33.8, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 3.8, "year": 2020,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings; centrally funded public housing places only"},
         "pension_spend": {"value": 5.1, "year": 2022,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 2.5, "year": 2022,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.131, "year": 2022,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 92.8, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.927, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 2.63, "year": 2023,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 18.7, "year": 2024,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 210.0, "year": 2026,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "US", "name": "United States", "timezones": ["America/New_York", "America/Chicago",
        "America/Denver", "America/Los_Angeles", "America/Phoenix", "America/Anchorage",
        "Pacific/Honolulu"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_private", "education": "ed_market",
                 "housing": "ho_market", "retirement": "re_flat", "energy": "en_fossil",
                 "speech": "sp_first_amendment", "voting": "vo_fptp", "work": "wo_at_will",
                 "defence": "de_power", "immigration": "im_points", "justice": "ju_tough",
                 "family": "fa_none"},
     "indicators": {
         "health_public": {"value": 54.0, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.4, "year": 2021,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 3.4, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 15.2, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 27.7, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 3.6, "year": 2019,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 7.3, "year": 2023,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 0.6, "year": 2023,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.112, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 384.4, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.729, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 1.01, "year": 2024,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 11.1, "year": 2024,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 542.0, "year": 2023,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "UK", "name": "United Kingdom", "timezones": ["Europe/London"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_continental", "healthcare": "hc_public", "education": "ed_deferred",
                 "housing": "ho_subsidy", "retirement": "re_flat", "energy": "en_carbon_tax",
                 "speech": "sp_hate_limits", "voting": "vo_fptp", "work": "wo_minimum",
                 "defence": "de_alliance", "immigration": "im_controlled", "justice": "ju_tough",
                 "family": "fa_universal"},
     "indicators": {
         "health_public": {"value": 81.8, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.9, "year": 2021,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 2.3, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 17.1, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 35.3, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 16.4, "year": 2022,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings; England only"},
         "pension_spend": {"value": 7.1, "year": 2022,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 1.9, "year": 2022,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.155, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 217.4, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.833, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 23.64, "year": 2024,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 40.2, "year": 2024,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 136.0, "year": 2026,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population; England and Wales"},
     }},
    {"code": "CA", "name": "Canada", "timezones": ["America/Toronto", "America/Vancouver",
        "America/Edmonton", "America/Winnipeg", "America/Halifax", "America/St_Johns"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_mixed", "education": "ed_free_selective",
                 "housing": "ho_market", "retirement": "re_flat", "energy": "en_carbon_tax",
                 "speech": "sp_hate_limits", "voting": "vo_fptp", "work": "wo_minimum",
                 "defence": "de_alliance", "immigration": "im_points", "justice": "ju_standard",
                 "family": "fa_targeted"},
     "indicators": {
         "health_public": {"value": 70.2, "year": 2024,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 4.8, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 1.3, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 22.2, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 33.2, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 3.5, "year": 2022,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 5.9, "year": 2022,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 1.6, "year": 2022,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.127, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 190.7, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.933, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 5.01, "year": 2025,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 30.2, "year": 2024,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 98.0, "year": 2023,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "DE", "name": "Germany", "timezones": ["Europe/Berlin"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_continental", "healthcare": "hc_insurance", "education": "ed_vocational",
                 "housing": "ho_subsidy", "retirement": "re_earnings", "energy": "en_deposit",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_bargaining",
                 "defence": "de_alliance", "immigration": "im_open", "justice": "ju_standard",
                 "family": "fa_universal"},
     "indicators": {
         "health_public": {"value": 79.1, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.2, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 1.9, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 19.8, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 39.3, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 2.6, "year": 2021,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 10.8, "year": 2021,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 2.7, "year": 2021,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.19, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 329.7, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.914, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 6.49, "year": 2025,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 49.0, "year": 2024,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 69.0, "year": 2025,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "FR", "name": "France", "timezones": ["Europe/Paris"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_continental", "healthcare": "hc_insurance", "education": "ed_free",
                 "housing": "ho_cooperative", "retirement": "re_generous", "energy": "en_nuclear",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_mandated_leave",
                 "defence": "de_power", "immigration": "im_controlled", "justice": "ju_standard",
                 "family": "fa_pronatal"},
     "indicators": {
         "health_public": {"value": 68.4, "year": 2024,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.3, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 2.1, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 13.8, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 46.1, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 14.0, "year": 2018,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 13.4, "year": 2022,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 2.6, "year": 2022,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.218, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 41.4, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.959, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 7.79, "year": 2024,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 98.0, "year": 2024,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 131.0, "year": 2026,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    # NL energy changed from en_hydro to en_carbon_tax 2026-08-29. The Dutch grid is
    # 253.6 g/kWh, which is not the clean grid en_hydro claims, and the Netherlands
    # prices carbon through the EU ETS plus a national industrial CO2 levy. Sources
    # are on the en_carbon_tax option in policies.py.
    {"code": "NL", "name": "Netherlands", "timezones": ["Europe/Amsterdam"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_continental", "healthcare": "hc_insurance", "education": "ed_vocational",
                 "housing": "ho_social", "retirement": "re_super", "energy": "en_carbon_tax",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_bargaining",
                 "defence": "de_alliance", "immigration": "im_open", "justice": "ju_rehab",
                 "family": "fa_targeted"},
     "indicators": {
         "health_public": {"value": 68.4, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.2, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 1.9, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 16.2, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 38.0, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 34.1, "year": 2021,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 6.4, "year": 2021,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 1.6, "year": 2021,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.147, "year": 2024,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 253.6, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.91, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 1.46, "year": 2023,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 72.1, "year": 2024,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 70.0, "year": 2025,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "DK", "name": "Denmark", "timezones": ["Europe/Copenhagen"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_nordic", "healthcare": "hc_mixed", "education": "ed_free",
                 "housing": "ho_cooperative", "retirement": "re_earnings", "energy": "en_carbon_tax",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_bargaining",
                 "defence": "de_alliance", "immigration": "im_controlled", "justice": "ju_rehab",
                 "family": "fa_universal"},
     "indicators": {
         "health_public": {"value": 83.4, "year": 2024,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 6.4, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 2.4, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 14.2, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 41.9, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 21.3, "year": 2022,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 7.5, "year": 2021,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 3.2, "year": 2021,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.166, "year": 2022,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 114.4, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.98, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 1.13, "year": 2022,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 81.6, "year": 2023,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 70.0, "year": 2025,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    # SE housing changed from ho_cooperative to ho_subsidy 2026-08-29. OECD PH4.2
    # excludes Sweden from the social rental housing indicator on the ground that
    # municipal housing company rents are not below market, so the axis this cell
    # feeds has no Swedish social housing to report. The reasoning and the sources
    # are on the ho_subsidy option in policies.py.
    {"code": "SE", "name": "Sweden", "timezones": ["Europe/Stockholm"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_nordic", "healthcare": "hc_mixed", "education": "ed_free",
                 "housing": "ho_subsidy", "retirement": "re_earnings", "energy": "en_hydro",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_mandated_leave",
                 "defence": "de_militia", "immigration": "im_points", "justice": "ju_rehab",
                 "family": "fa_leave"},
     "indicators": {
         "health_public": {"value": 86.1, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 7.3, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 2.0, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 21.4, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 41.3, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": None, "year": 2022,
                            "source": "n/a",
                            "na_reason": "municipal housing associations house a large share of low-income households, but rents are not below market, so the OECD does not count them as social housing"},
         "pension_spend": {"value": 8.0, "year": 2021,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 3.3, "year": 2021,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.142, "year": 2024,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 35.3, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.946, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 0.64, "year": 2022,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 88.0, "year": 2024,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 106.0, "year": 2025,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "NO", "name": "Norway", "timezones": ["Europe/Oslo"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_nordic", "healthcare": "hc_mixed", "education": "ed_free",
                 "housing": "ho_subsidy", "retirement": "re_earnings", "energy": "en_hydro",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_transparency",
                 "defence": "de_alliance", "immigration": "im_points", "justice": "ju_rehab",
                 "family": "fa_leave"},
     "indicators": {
         "health_public": {"value": 86.1, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.4, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 2.1, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 18.2, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 44.3, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 4.1, "year": 2022,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings; municipal dwellings only, about 75% of the stock"},
         "pension_spend": {"value": 6.5, "year": 2021,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 2.8, "year": 2021,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.173, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 28.1, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.953, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 3.65, "year": 2021,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 72.0, "year": 2022,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 54.0, "year": 2026,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "FI", "name": "Finland", "timezones": ["Europe/Helsinki"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_nordic", "healthcare": "hc_mixed", "education": "ed_free",
                 "housing": "ho_subsidy", "retirement": "re_earnings", "energy": "en_hydro",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_bargaining",
                 "defence": "de_militia", "immigration": "im_open", "justice": "ju_rehab",
                 "family": "fa_universal"},
     "indicators": {
         "health_public": {"value": 81.1, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 6.4, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 2.3, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 9.2, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 43.0, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 10.9, "year": 2021,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 12.2, "year": 2021,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 3.1, "year": 2021,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.243, "year": 2024,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 57.5, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.946, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 3.99, "year": 2023,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 88.8, "year": 2022,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 58.0, "year": 2025,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "EE", "name": "Estonia", "timezones": ["Europe/Tallinn"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_flat", "healthcare": "hc_mixed", "education": "ed_free",
                 "housing": "ho_market", "retirement": "re_super", "energy": "en_carbon_tax",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_minimum",
                 "defence": "de_alliance", "immigration": "im_open", "justice": "ju_tough",
                 "family": "fa_targeted"},
     "indicators": {
         "health_public": {"value": 75.8, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.2, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 3.4, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 14.9, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 32.8, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 1.1, "year": 2017,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 6.8, "year": 2021,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 3.0, "year": 2021,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.157, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 319.2, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.969, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 4.66, "year": 2023,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 19.1, "year": 2021,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 128.0, "year": 2026,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "CH", "name": "Switzerland", "timezones": ["Europe/Zurich"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_insurance", "education": "ed_vocational",
                 "housing": "ho_subsidy", "retirement": "re_super", "energy": "en_hydro",
                 "speech": "sp_hate_limits", "voting": "vo_direct", "work": "wo_minimum",
                 "defence": "de_militia", "immigration": "im_controlled", "justice": "ju_standard",
                 "family": "fa_targeted"},
     "indicators": {
         "health_public": {"value": 33.1, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 4.9, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 0.7, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 31.1, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 27.2, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 8.0, "year": 2013,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 6.6, "year": 2021,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 1.7, "year": 2021,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.083, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 39.2, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.967, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 3.6, "year": 2023,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 51.5, "year": 2021,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 78.0, "year": 2026,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    # SG energy changed from en_hydro to en_carbon_tax 2026-08-29. The public
    # transport half of en_hydro is true of Singapore and the clean grid half is
    # not: the grid is 497.1 g/kWh, close to the fossil end of the axis. Singapore
    # has taxed carbon since 2019 and raised the rate five-fold in 2024. Sources are
    # on the en_carbon_tax option in policies.py. The speech cell is unchanged and
    # Singapore is now the only country on sp_order.
    {"code": "SG", "name": "Singapore", "timezones": ["Asia/Singapore"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_savings", "education": "ed_market",
                 "housing": "ho_singapore", "retirement": "re_private", "energy": "en_carbon_tax",
                 "speech": "sp_order", "voting": "vo_fptp", "work": "wo_at_will",
                 "defence": "de_conscript", "immigration": "im_points", "justice": "ju_corporal",
                 "family": "fa_none"},
     "indicators": {
         "health_public": {"value": 58.5, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 2.2, "year": 2024,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 2.8, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 48.7, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 12.1, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "grid_carbon": {"value": 497.1, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.4, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 16.88, "year": 2025,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "incarceration": {"value": 178.0, "year": 2024,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    # JP changed on two cells 2026-08-29. Energy en_hydro to en_carbon_tax: the
    # grid has been coal and gas heavy since Fukushima at 477.3 g/kWh, and Japan
    # has had a carbon tax since 2012 with the GX-ETS mandatory from April 2026.
    # Speech sp_order to sp_hate_limits: at 0.847 Japan sits above the UK and
    # Israel, both of which are on sp_hate_limits, so the lower bucket was not
    # supportable. This is the weaker of the two speech moves and the caveat, that
    # the 2016 hate speech act carries no penalty, is recorded on the option in
    # policies.py rather than hidden.
    {"code": "JP", "name": "Japan", "timezones": ["Asia/Tokyo"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_insurance", "education": "ed_market",
                 "housing": "ho_subsidy", "retirement": "re_earnings", "energy": "en_carbon_tax",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_minimum",
                 "defence": "de_alliance", "immigration": "im_closed", "justice": "ju_rehab",
                 "family": "fa_targeted"},
     "indicators": {
         "health_public": {"value": 84.8, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 3.3, "year": 2021,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 1.4, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 2.8, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 34.1, "year": 2021,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 3.1, "year": 2018,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 9.2, "year": 2022,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 2.0, "year": 2022,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.175, "year": 2021,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 477.3, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.847, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 8.92, "year": 2024,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 15.2, "year": 2023,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 33.0, "year": 2025,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    # KR changed on two cells 2026-08-29. Energy en_nuclear to en_carbon_tax:
    # nuclear is the largest single source at 31.1% of generation but coal and LNG
    # are about 56% together, so "most power from reactors" is false, and the
    # K-ETS has priced emissions since 2015. Speech sp_order to sp_hate_limits:
    # V-Dem puts Korean freedom of expression at 0.933, level with Canada, so a
    # public-order restriction cell was a claim about Korea that the measure
    # contradicts. Sources are on both options in policies.py.
    {"code": "KR", "name": "South Korea", "timezones": ["Asia/Seoul"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_insurance", "education": "ed_market",
                 "housing": "ho_subsidy", "retirement": "re_earnings", "energy": "en_carbon_tax",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_at_will",
                 "defence": "de_conscript", "immigration": "im_closed", "justice": "ju_standard",
                 "family": "fa_none"},
     "indicators": {
         "health_public": {"value": 56.6, "year": 2024,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.4, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 2.6, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 3.5, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 32.0, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 8.9, "year": 2018,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 3.8, "year": 2022,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 1.7, "year": 2022,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.069, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 417.1, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.933, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 15.27, "year": 2024,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 16.3, "year": 2023,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 127.0, "year": 2026,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "IL", "name": "Israel", "timezones": ["Asia/Jerusalem"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_insurance", "education": "ed_free",
                 "housing": "ho_market", "retirement": "re_flat", "energy": "en_fossil",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_minimum",
                 "defence": "de_conscript", "immigration": "im_points", "justice": "ju_tough",
                 "family": "fa_targeted"},
     "indicators": {
         "health_public": {"value": 65.2, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 5.9, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 8.8, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 22.3, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 32.9, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": 1.8, "year": 2023,
                            "source": "OECD Affordable Housing Database PH4.2, social rental dwellings % of total dwellings"},
         "pension_spend": {"value": 4.5, "year": 2023,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 1.9, "year": 2023,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.108, "year": 2023,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 492.7, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.822, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 4.4, "year": 2022,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 45.8, "year": 2023,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 217.0, "year": 2023,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    {"code": "CL", "name": "Chile", "timezones": ["America/Santiago"],
     "nonTaxRevenue": 0.0,
     "choices": {"tax": "tax_anglo", "healthcare": "hc_insurance", "education": "ed_market",
                 "housing": "ho_market", "retirement": "re_private", "energy": "en_carbon_tax",
                 "speech": "sp_hate_limits", "voting": "vo_proportional", "work": "wo_minimum",
                 "defence": "de_alliance", "immigration": "im_controlled", "justice": "ju_tough",
                 "family": "fa_targeted"},
     "indicators": {
         "health_public": {"value": 48.5, "year": 2024,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 4.9, "year": 2022,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 1.6, "year": 2024,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 7.8, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "tax_take": {"value": 23.9, "year": 2022,
                      "source": "OECD Global Revenue Statistics Database, total tax revenue (all levels of government) % of GDP"},
         "social_housing": {"value": None, "year": 2022,
                            "source": "n/a",
                            "na_reason": "the OECD records virtually no social rental sector"},
         "pension_spend": {"value": 3.7, "year": 2023,
                           "source": "OECD SOCX, public expenditure on old age and survivors cash benefits % of GDP"},
         "family_spend": {"value": 1.8, "year": 2023,
                          "source": "OECD SOCX, public expenditure on family benefits (cash and in kind) % of GDP"},
         "redistribution": {"value": 0.043, "year": 2022,
                            "source": "OECD Income Distribution Database, market Gini less disposable Gini, whole population"},
         "grid_carbon": {"value": 289.5, "year": 2025,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.926, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": 9.58, "year": 2021,
                                "source": "Gallagher, Election indices (Trinity College Dublin), 16 June 2025 edition, least squares index at the most recent national legislative election"},
         "bargaining": {"value": 19.3, "year": 2023,
                        "source": "OECD/AIAS ICTWSS via OECD Data Explorer, collective bargaining coverage, % of employees with the right to bargain"},
         "incarceration": {"value": 329.0, "year": 2025,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
    # AE retirement changed from re_private to re_generous 2026-08-29. There are no
    # mandatory individual accounts here: GPSSA is a contributory pay-as-you-go
    # defined-benefit scheme paying up to 100% of the final five years' average
    # salary, with a pension age of 60. Sources and the expatriate caveat are on
    # the re_generous option in policies.py.
    {"code": "AE", "name": "United Arab Emirates", "timezones": ["Asia/Dubai"],
     # THE ONLY NON-ZERO CELL IN THE FILE, and the reason the field exists.
     # IMF general government revenue for the UAE is 27.8% of GDP in 2024,
     # against a total TAX take of about 16.0. The 11.8 points between them
     # are hydrocarbon and investment income, which no tax-to-GDP series
     # captures a cent of. It was modelled as tax until 2026-08-30, which
     # meant a visitor who moved the UAE off tax_minimal lost the oil.
     # https://www.imf.org/external/datamapper/rev@FPP/ARE
     # Cross-checked against the same dataset's expenditure series (21.4%,
     # and 27.8 less 21.4 is the 6.4% surplus the 2025 Article IV states)
     # and against CBUAE's Quarterly Economic Review (26.9% in H1 2024).
     "nonTaxRevenue": 11.8,
     "choices": {"tax": "tax_minimal", "healthcare": "hc_mixed", "education": "ed_vocational",
                 "housing": "ho_market", "retirement": "re_generous", "energy": "en_fossil",
                 "speech": "sp_restricted", "voting": "vo_none", "work": "wo_at_will",
                 "defence": "de_power", "immigration": "im_guest", "justice": "ju_corporal",
                 "family": "fa_none"},
     "indicators": {
         "health_public": {"value": 66.8, "year": 2023,
                           "source": "WHO GHED, domestic general government health expenditure % of current health expenditure"},
         "education_spend": {"value": 3.9, "year": 2021,
                             "source": "World Bank, government expenditure on education % of GDP"},
         "military_burden": {"value": 5.6, "year": 2014,
                             "source": "World Bank / SIPRI, military expenditure % of GDP"},
         "foreign_born": {"value": 74.0, "year": 2024,
                          "source": "UN DESA / World Bank, international migrant stock % of population"},
         "grid_carbon": {"value": 467.5, "year": 2024,
                         "source": "Our World in Data / Ember, carbon intensity of electricity generation gCO2 per kWh"},
         "expression": {"value": 0.063, "year": 2025,
                        "source": "V-Dem via Our World in Data, freedom of expression and alternative sources of information index (v2x_freexp_altinf), central estimate"},
         "disproportionality": {"value": None, "year": 2024,
                                "source": "n/a",
                                "na_reason": "no competitive national elections"},
         "incarceration": {"value": 104.0, "year": 2014,
                           "source": "World Prison Brief, prison population rate per 100,000 of national population"},
     }},
]
