"""Regenerate sitemap.xml from what the repo actually serves.

    python tools/build_sitemap.py            # write it
    python tools/build_sitemap.py --check    # exit 1 if it is out of date

Written 09/09/2026, after Search Console reported **115 pages "Discovered -
currently not indexed"**. The cause was not an error: sitemap.xml was a
hand-maintained file listing ten URLs, and Ghostwriters alone had grown to 135
pages that appeared in no sitemap at all. Google had found them by following
links, had no priority signal for any of them, and deprioritised the lot.

Hand-maintenance was never going to hold, because Ghostwriters gains an essay
EVERY DAY. A static sitemap is stale again the next morning.

WHAT COUNTS AS INDEXABLE, and why the rule is the page's own declaration:
a page is included unless it says `noindex`. That is the same signal Google
obeys, so the sitemap cannot contradict the page - which is exactly the
"Excluded by noindex tag" and "Page with redirect" noise the old file was
hand-curated to avoid. To keep a page out of search, put `noindex` in the page.
Do not maintain a second list here; that is the arrangement that just failed.

Subdomains (crowdwise., dcf., one-story., aftertimes.) are NOT listed: a sitemap
may only carry URLs inside its own property. The redirect stubs at /crowdwise/,
/one-story/ and friends carry noindex and are dropped by the rule above.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = "https://charlietrenorden.com"
OUT = ROOT / "sitemap.xml"

#: Never submitted, whatever the page says. Private, or served by another sitemap.
SKIP_PREFIXES = (
    "stats/",          # key-gated behind Cloudflare Access, and Disallowed in robots.txt
    "chronoscape/",    # ships its own sitemap, listed separately in robots.txt
    "bookmark/tools/", # prototypes, not pages
    "assets/",         # og-card-source.html and friends are RENDER SOURCES, not pages
)

#: Files that are not pages even though they sit at the root and end in .html.
SKIP_SUFFIXES = (
    "designs.html", "designs2.html",                      # Property Atlas mockups
    "icons.html", "icons2.html", "icons3.html",
    "icons4.html", "icons5.html",
)

#: The Search Console verification file. Submitting it is harmless but silly, and it
#: would show up as a page in the index report - which is what started all this.
SKIP_EXACT = ("google125c0b04f22760d0.html",)

#: PATHS ON THIS DOMAIN THAT ARE NOT IN THIS REPO.
#: Setting a custom domain on a user Pages site also serves that account's PROJECT
#: Pages sites underneath it, so these are live at charlietrenorden.com/<name>/ while
#: living in their own repositories. A generator that only walks this repo drops them
#: silently - which it did on the first run here, quietly deleting four URLs the old
#: hand-written sitemap had listed for months. They belong in OUR sitemap because
#: they are served from OUR domain.
EXTERNAL_PATHS = (
    "shortfall/",
    "consensus-drift/",
    "lindy-effect/",
    "woop-woop/",
    "photocopy/",
)

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by tools/build_sitemap.py - do not hand-edit, it will be overwritten.

  A page is included unless it declares noindex. To keep something out of search,
  put noindex in the PAGE; a second list here is what went stale and left 115
  Ghostwriters pages out of every sitemap until 09/09/2026.
-->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
"""


def _last_commit_date(path: Path) -> str:
    """The file's last AUTHOR date, so lastmod means something and stays put.

    %as, not %cs. Committer date is rewritten by every rebase, and this repo takes
    pushes from several sessions plus a bot, so a pull would silently change the
    lastmod of every page and produce a 154-line diff out of nothing - which the
    daily job would then commit, every day, forever. Author date survives a rebase.
    Caught by test_the_sitemap_is_up_to_date within an hour of the file landing.
    """
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%as", "--", str(path.relative_to(ROOT))],
            cwd=ROOT, capture_output=True, text=True, timeout=20)
        return (out.stdout or "").strip() or "2026-01-01"
    except Exception:  # noqa: BLE001 - a date is a nicety, never fail the build
        return "2026-01-01"


def indexable_pages() -> list[tuple[str, str]]:
    """(url, lastmod) for every page that should be submitted."""
    rows = []
    for path in sorted(ROOT.rglob("*.html")):
        rel = path.relative_to(ROOT).as_posix()
        if rel.startswith(".") or "/node_modules/" in rel or rel.startswith("node_modules/"):
            continue
        if any(rel.startswith(p) for p in SKIP_PREFIXES):
            continue
        if rel in SKIP_EXACT or rel.endswith(SKIP_SUFFIXES):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        # The page's own declaration decides it. Matches what Google obeys.
        if "noindex" in text:
            continue
        # /a/b/index.html is served as /a/b/ - list the directory form, never both.
        url = BASE + "/" + (rel[: -len("index.html")] if rel.endswith("index.html") else rel)
        rows.append((url, _last_commit_date(path)))

    # The project-Pages paths, which this repo cannot see. Dated from the newest
    # thing in this repo rather than invented - they change on their own schedule
    # and a made-up lastmod is worse than a roughly-right one.
    newest = max((d for _, d in rows), default="2026-01-01")
    for extra in EXTERNAL_PATHS:
        rows.append((f"{BASE}/{extra}", newest))

    return sorted(set(rows))


def render(rows: list[tuple[str, str]]) -> str:
    body = "".join(
        f"  <url>\n    <loc>{u}</loc>\n    <lastmod>{d}</lastmod>\n  </url>\n"
        for u, d in rows)
    return HEADER + body + "</urlset>\n"


def main() -> int:
    rows = indexable_pages()
    doc = render(rows)
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current.strip() != doc.strip():
            print(f"sitemap.xml is out of date - {len(rows)} pages should be listed. "
                  f"Run: python tools/build_sitemap.py", file=sys.stderr)
            return 1
        print(f"sitemap.xml is current ({len(rows)} pages).")
        return 0
    OUT.write_text(doc, encoding="utf-8", newline="\n")
    print(f">>> sitemap.xml: {len(rows)} pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
