"""Split the shelf into what the page needs FIRST and what it needs a beat later.

    python tools/build_site_data.py           # writes shelf.js and texts.js
    python tools/build_site_data.py --check   # fail if either is out of date

books.js stays the master and every pipeline tool keeps reading and writing it.
This only produces the two files the SITE loads, because at 1812 books the single
file is 666KB and it blocks first paint - and 388KB of that is descriptions, of
which the page shows exactly one at a time.

  shelf.js  300KB, blocking. Everything the shortlist, the scoring and the
            spines need: title, author, year, setting, form, subject, mood,
            length, prose, effort.
  texts.js  388KB, deferred. The description and its source link, keyed by
            title. Arrives after the shelf has already drawn.

The page must therefore render correctly with texts.js ABSENT, not merely
render late - a reader on a slow connection sees the shelf, the questions and
the month's pick with its title and chips, and the description fills in. Nothing
about the choice of book depends on it.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
BOOKS = ROOT / "books.js"
SHELF = ROOT / "shelf.js"
TEXTS = ROOT / "texts.js"

#: Fields the page needs before it can draw anything. Everything else waits.
FIRST = ("t", "a", "y", "set", "f", "tags", "mood", "len", "sty", "dem", "soft")


def records() -> list[dict]:
    """books.js is a JS literal, not JSON, so it is read with node - which is
    also the only reader whose opinion matters, since the browser is what has to
    parse it. A regex reader here would accept shapes the browser rejects."""
    import subprocess
    out = subprocess.run(
        ["node", "-e",
         "global.window={};require(process.argv[1]);"
         "process.stdout.write(JSON.stringify(window.SHELF))",
         str(BOOKS)],
        capture_output=True, text=True, check=True)
    return json.loads(out.stdout)


def build() -> tuple[str, str]:
    recs = records()
    shelf = [{k: b[k] for k in FIRST if k in b} for b in recs]
    texts = {b["t"]: [b["why"], b["src"]] for b in recs}
    head = ("/* GENERATED by tools/build_site_data.py from books.js. Do not edit:\n"
            "   books.js is the master and the next build overwrites this. */\n")
    # texts.js CALLS BACK rather than leaving the page to guess when it arrived.
    # It defers, so it runs after the inline app script has already rendered
    # once. A load listener for that is timing-dependent, and the first attempt
    # at one was silently nested inside the theme handler and never fired.
    return (head + "window.SHELF = " + json.dumps(shelf, ensure_ascii=False,
                                                  separators=(",", ":")) + ";\n",
            head + "window.TEXTS = " + json.dumps(texts, ensure_ascii=False,
                                                  separators=(",", ":")) + ";\n"
            + "if (window.onTexts) window.onTexts();\n")


def main(argv: list[str]) -> int:
    shelf, texts = build()
    if "--check" in argv:
        stale = []
        for path, want in ((SHELF, shelf), (TEXTS, texts)):
            if not path.exists() or path.read_text(encoding="utf-8") != want:
                stale.append(path.name)
        if stale:
            print("STALE, rerun tools/build_site_data.py: " + ", ".join(stale))
            return 1
        print("shelf.js and texts.js are in step with books.js")
        return 0
    SHELF.write_text(shelf, encoding="utf-8")
    TEXTS.write_text(texts, encoding="utf-8")
    n = len(json.loads(shelf[shelf.index("= ") + 2:-2]))
    print(f"{n} books")
    print(f"  shelf.js {len(shelf)/1024:>6.0f}KB  blocking")
    print(f"  texts.js {len(texts)/1024:>6.0f}KB  deferred")
    print(f"  books.js {BOOKS.stat().st_size/1024:>6.0f}KB  master, not served")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
